// Auto-generated by php artisan data-table:types
// Do not edit manually

declare namespace DataTable {
    export interface Column {
        id: string;
        label: string;
        type?: string;
        sortable?: boolean;
        filterable?: boolean;
        visible?: boolean;
        options?: unknown[] | null;
        min?: number | null;
        max?: number | null;
        icon?: string | null;
        searchThreshold?: number | null;
        group?: string | null;
        editable?: boolean;
        currency?: string | null;
        locale?: string | null;
        summary?: string | null;
        toggleable?: boolean;
        responsivePriority?: number | null;
        internalName?: string | null;
        relation?: string | null;
        prefix?: string | null;
        suffix?: string | null;
        tooltip?: string | null;
        description?: string | null;
        lineClamp?: number | null;
        iconMap?: unknown[] | null;
        colorMap?: unknown[] | null;
        selectOptions?: unknown[] | null;
        html?: boolean;
        markdown?: boolean;
        bulleted?: boolean;
        stacked?: unknown[] | null;
        rowIndex?: boolean;
        avatarColumn?: string | null;
        hasDynamicSuffix?: boolean;
        computedFrom?: unknown[] | null;
        colSpan?: number | null;
        autoHeight?: boolean;
        valueGetter?: string | null;
        valueFormatter?: string | null;
        headerFilter?: boolean;
        sparkline?: string | null;
        treeParent?: string | null;
    }

    export interface DataTableResponse {
        data: unknown[];
        columns: unknown[];
        quickViews: unknown[];
        meta: unknown;
        exportUrl?: string | null;
        footer?: unknown[] | null;
        selectAllUrl?: string | null;
        summary?: unknown[] | null;
        config?: unknown[] | null;
        toggleUrl?: string | null;
        enumOptions?: unknown[] | null;
        reorderUrl?: string | null;
        importUrl?: string | null;
        groupByColumn?: string | null;
        pinnedTopRows?: unknown[] | null;
        pinnedBottomRows?: unknown[] | null;
        actionRules?: unknown[] | null;
        analytics?: unknown[] | null;
    }

    export interface DataTableMeta {
        currentPage: number;
        lastPage: number;
        perPage: number;
        total: number;
        sorts?: unknown[];
        filters?: unknown[];
        paginationType?: string;
        nextCursor?: string | null;
        prevCursor?: string | null;
    }

    export interface QuickView {
        id: string;
        label: string;
        params?: unknown[];
        icon?: string | null;
        active?: boolean;
        columns?: unknown[] | null;
    }

    export interface AnnouncementDataTable {
        id: number;
        title: string;
        level: string;
        scope: string;
        is_active: boolean;
        starts_at?: string | null;
        ends_at?: string | null;
        organization_name?: string | null;
        creator_name?: string | null;
        created_at?: string | null;
    }

    export interface CategoryDataTable {
        id: number;
        name: string;
        slug: string;
        type: string;
        parent_id?: number | null;
        parent_name?: string | null;
        created_at?: string | null;
    }

    export interface OrganizationDataTable {
        id: number;
        name: string;
        slug: string;
        owner_name?: string | null;
        created_at?: string | null;
    }

    export interface PostDataTable {
        id: number;
        title: string;
        is_published: boolean;
        published_at?: string | null;
        views: number;
        author_name?: string | null;
        created_at?: string | null;
    }

    export interface UserDataTable {
        id: number;
        hash_id: string;
        name: string;
        email: string;
        avatar?: string | null;
        status: string;
        onboarding_completed: boolean;
        organizations_count: number;
        first_organization_name?: string | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
