// Auto-generated by php artisan data-table:types
// Do not edit manually

declare namespace DataTable {
    export interface Column {
        id: string;
        label: string;
        type?: string;
        sortable?: boolean;
        filterable?: boolean;
        visible?: boolean;
        options?: unknown[] | null;
        min?: number | null;
        max?: number | null;
        icon?: string | null;
        searchThreshold?: number | null;
        group?: string | null;
        editable?: boolean;
        currency?: string | null;
        locale?: string | null;
        summary?: string | null;
        toggleable?: boolean;
        responsivePriority?: number | null;
        internalName?: string | null;
        relation?: string | null;
        prefix?: string | null;
        suffix?: string | null;
        tooltip?: string | null;
        description?: string | null;
        lineClamp?: number | null;
        iconMap?: unknown[] | null;
        colorMap?: unknown[] | null;
        selectOptions?: unknown[] | null;
        html?: boolean;
        markdown?: boolean;
        bulleted?: boolean;
        stacked?: unknown[] | null;
        rowIndex?: boolean;
    }

    export interface DataTableResponse {
        data: unknown[];
        columns: unknown[];
        quickViews: unknown[];
        meta: unknown;
        exportUrl?: string | null;
        footer?: unknown[] | null;
        selectAllUrl?: string | null;
        summary?: unknown[] | null;
        config?: unknown[] | null;
        toggleUrl?: string | null;
        enumOptions?: unknown[] | null;
        reorderUrl?: string | null;
        importUrl?: string | null;
        groupByColumn?: string | null;
    }

    export interface DataTableMeta {
        currentPage: number;
        lastPage: number;
        perPage: number;
        total: number;
        sorts?: unknown[];
        filters?: unknown[];
        paginationType?: string;
        nextCursor?: string | null;
        prevCursor?: string | null;
    }

    export interface QuickView {
        id: string;
        label: string;
        params?: unknown[];
        icon?: string | null;
        active?: boolean;
        columns?: unknown[] | null;
    }

    export interface UserDataTable {
        id: number;
        name: string;
        email: string;
        avatar?: string | null;
        onboarding_completed: boolean;
        created_at?: string | null;
        updated_at?: string | null;
    }

}
