CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "governor_roles" ("name" varchar not null, "description" varchar, "created_at" datetime, "updated_at" datetime, primary key ("name"));
CREATE TABLE IF NOT EXISTS "governor_groups" ("name" varchar not null, "created_at" datetime, "updated_at" datetime, primary key ("name"));
CREATE TABLE IF NOT EXISTS "governor_entities" ("name" varchar not null, "group_name" varchar, "created_at" datetime, "updated_at" datetime, foreign key("group_name") references "governor_groups"("name") on delete SET NULL on update CASCADE, primary key ("name"));
CREATE TABLE IF NOT EXISTS "governor_actions" ("name" varchar not null, "created_at" datetime, "updated_at" datetime, primary key ("name"));
CREATE TABLE IF NOT EXISTS "governor_ownerships" ("name" varchar not null, "created_at" datetime, "updated_at" datetime, primary key ("name"));
CREATE TABLE IF NOT EXISTS "governor_role_user" ("id" integer primary key autoincrement not null, "role_name" varchar not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("role_name") references "governor_roles"("name") on delete CASCADE on update CASCADE, foreign key("user_id") references "users"("id") on delete CASCADE on update CASCADE);
CREATE UNIQUE INDEX "governor_role_user_role_name_user_id_unique" on "governor_role_user" ("role_name", "user_id");
CREATE TABLE IF NOT EXISTS "governor_teams" ("id" integer primary key autoincrement not null, "governor_owned_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "name" varchar not null, "description" text, foreign key("governor_owned_by") references "users"("id") on delete SET NULL on update CASCADE);
CREATE TABLE IF NOT EXISTS "governor_team_user" ("team_id" integer not null, "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("team_id") references "governor_teams"("id") on delete CASCADE on update CASCADE, foreign key("user_id") references "users"("id") on delete CASCADE on update CASCADE);
CREATE INDEX "governor_team_user_team_id_index" on "governor_team_user" ("team_id");
CREATE INDEX "governor_team_user_user_id_index" on "governor_team_user" ("user_id");
CREATE TABLE IF NOT EXISTS "governor_team_invitations" ("id" integer primary key autoincrement not null, "governor_owned_by" integer, "team_id" integer not null, "created_at" datetime, "updated_at" datetime, "email" varchar not null, "token" varchar not null, foreign key("team_id") references "governor_teams"("id") on delete CASCADE on update CASCADE);
CREATE TABLE IF NOT EXISTS "governor_teamables" ("team_id" integer not null, "teamable_id" integer not null, "teamable_type" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("team_id") references "governor_teams"("id") on delete CASCADE on update CASCADE);
CREATE TABLE IF NOT EXISTS "governor_permissions" ("id" integer primary key autoincrement not null, "role_name" varchar, "entity_name" varchar not null, "action_name" varchar not null, "ownership_name" varchar not null, "team_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("role_name") references "governor_roles"("name") on delete CASCADE on update CASCADE, foreign key("entity_name") references "governor_entities"("name") on delete CASCADE on update CASCADE, foreign key("action_name") references "governor_actions"("name") on delete CASCADE on update CASCADE, foreign key("ownership_name") references "governor_ownerships"("name") on delete CASCADE on update CASCADE, foreign key("team_id") references "governor_teams"("id") on delete SET NULL on update CASCADE);
CREATE UNIQUE INDEX "governor_permissions_unique_key" on "governor_permissions" ("role_name", "entity_name", "action_name", "ownership_name");
CREATE TABLE IF NOT EXISTS "scheduled_notifications" ("id" integer primary key autoincrement not null, "target_id" varchar, "target_type" varchar not null, "target" text not null, "notification_type" varchar not null, "notification" text not null, "send_at" datetime not null, "sent_at" datetime, "rescheduled_at" datetime, "cancelled_at" datetime, "created_at" datetime, "updated_at" datetime, "meta" text);
CREATE TABLE IF NOT EXISTS "workflows" ("id" integer primary key autoincrement not null, "class" text not null, "arguments" text, "output" text, "status" varchar not null default 'pending', "created_at" datetime, "updated_at" datetime);
CREATE INDEX "workflows_status_index" on "workflows" ("status");
CREATE TABLE IF NOT EXISTS "workflow_logs" ("id" integer primary key autoincrement not null, "stored_workflow_id" integer not null, "index" integer not null, "now" datetime not null, "class" text not null, "result" text, "created_at" datetime, foreign key("stored_workflow_id") references "workflows"("id"));
CREATE UNIQUE INDEX "workflow_logs_stored_workflow_id_index_unique" on "workflow_logs" ("stored_workflow_id", "index");
CREATE INDEX "workflow_logs_stored_workflow_id_index" on "workflow_logs" ("stored_workflow_id");
CREATE TABLE IF NOT EXISTS "workflow_signals" ("id" integer primary key autoincrement not null, "stored_workflow_id" integer not null, "method" text not null, "arguments" text, "created_at" datetime, foreign key("stored_workflow_id") references "workflows"("id"));
CREATE INDEX "workflow_signals_stored_workflow_id_created_at_index" on "workflow_signals" ("stored_workflow_id", "created_at");
CREATE INDEX "workflow_signals_stored_workflow_id_index" on "workflow_signals" ("stored_workflow_id");
CREATE TABLE IF NOT EXISTS "workflow_timers" ("id" integer primary key autoincrement not null, "stored_workflow_id" integer not null, "index" integer not null, "stop_at" datetime not null, "created_at" datetime, foreign key("stored_workflow_id") references "workflows"("id"));
CREATE INDEX "workflow_timers_stored_workflow_id_created_at_index" on "workflow_timers" ("stored_workflow_id", "created_at");
CREATE INDEX "workflow_timers_stored_workflow_id_index" on "workflow_timers" ("stored_workflow_id");
CREATE TABLE IF NOT EXISTS "workflow_exceptions" ("id" integer primary key autoincrement not null, "stored_workflow_id" integer not null, "class" text not null, "exception" text not null, "created_at" datetime, foreign key("stored_workflow_id") references "workflows"("id"));
CREATE INDEX "workflow_exceptions_stored_workflow_id_index" on "workflow_exceptions" ("stored_workflow_id");
CREATE TABLE IF NOT EXISTS "workflow_relationships" ("id" integer primary key autoincrement not null, "parent_workflow_id" integer, "parent_index" integer not null, "parent_now" datetime not null, "child_workflow_id" integer, foreign key("parent_workflow_id") references "workflows"("id"), foreign key("child_workflow_id") references "workflows"("id"));
CREATE INDEX "workflow_relationships_parent_workflow_id_index" on "workflow_relationships" ("parent_workflow_id");
CREATE INDEX "workflow_relationships_child_workflow_id_index" on "workflow_relationships" ("child_workflow_id");
CREATE TABLE IF NOT EXISTS "settings" ("id" integer primary key autoincrement not null, "group" varchar not null, "name" varchar not null, "locked" tinyint(1) not null default '0', "payload" text not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "settings_group_name_unique" on "settings" ("group", "name");
CREATE TABLE IF NOT EXISTS "lemon_squeezy_customers" ("id" integer primary key autoincrement not null, "billable_id" integer not null, "billable_type" varchar not null, "lemon_squeezy_id" varchar, "trial_ends_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "lemon_squeezy_customers_billable_id_billable_type_unique" on "lemon_squeezy_customers" ("billable_id", "billable_type");
CREATE UNIQUE INDEX "lemon_squeezy_customers_lemon_squeezy_id_unique" on "lemon_squeezy_customers" ("lemon_squeezy_id");
CREATE TABLE IF NOT EXISTS "lemon_squeezy_subscriptions" ("id" integer primary key autoincrement not null, "billable_type" varchar not null, "billable_id" integer not null, "type" varchar not null, "lemon_squeezy_id" varchar not null, "status" varchar not null, "product_id" varchar not null, "variant_id" varchar not null, "card_brand" varchar, "card_last_four" varchar, "pause_mode" varchar, "pause_resumes_at" datetime, "trial_ends_at" datetime, "renews_at" datetime, "ends_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "lemon_squeezy_subscriptions_billable_type_billable_id_index" on "lemon_squeezy_subscriptions" ("billable_type", "billable_id");
CREATE UNIQUE INDEX "lemon_squeezy_subscriptions_lemon_squeezy_id_unique" on "lemon_squeezy_subscriptions" ("lemon_squeezy_id");
CREATE TABLE IF NOT EXISTS "lemon_squeezy_orders" ("id" integer primary key autoincrement not null, "billable_type" varchar not null, "billable_id" integer not null, "lemon_squeezy_id" varchar not null, "customer_id" varchar not null, "identifier" varchar not null, "product_id" varchar not null, "variant_id" varchar not null, "order_number" integer not null, "currency" varchar not null, "subtotal" integer not null, "discount_total" integer not null, "tax" integer not null, "total" integer not null, "tax_name" varchar, "status" varchar not null, "receipt_url" varchar, "refunded" tinyint(1) not null, "refunded_at" datetime, "ordered_at" datetime not null, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "lemon_squeezy_orders_billable_type_billable_id_index" on "lemon_squeezy_orders" ("billable_type", "billable_id");
CREATE UNIQUE INDEX "lemon_squeezy_orders_lemon_squeezy_id_unique" on "lemon_squeezy_orders" ("lemon_squeezy_id");
CREATE UNIQUE INDEX "lemon_squeezy_orders_identifier_unique" on "lemon_squeezy_orders" ("identifier");
CREATE INDEX "lemon_squeezy_orders_product_id_index" on "lemon_squeezy_orders" ("product_id");
CREATE INDEX "lemon_squeezy_orders_variant_id_index" on "lemon_squeezy_orders" ("variant_id");
CREATE UNIQUE INDEX "lemon_squeezy_orders_order_number_unique" on "lemon_squeezy_orders" ("order_number");
CREATE TABLE IF NOT EXISTS "lemon_squeezy_license_keys" ("id" integer primary key autoincrement not null, "lemon_squeezy_id" varchar not null, "license_key" varchar not null, "status" varchar not null, "order_id" varchar not null, "product_id" varchar not null, "disabled" tinyint(1) not null, "activation_limit" integer, "instances_count" integer not null, "expires_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("order_id") references "lemon_squeezy_orders"("lemon_squeezy_id"));
CREATE UNIQUE INDEX "lemon_squeezy_license_keys_lemon_squeezy_id_unique" on "lemon_squeezy_license_keys" ("lemon_squeezy_id");
CREATE UNIQUE INDEX "lemon_squeezy_license_keys_license_key_unique" on "lemon_squeezy_license_keys" ("license_key");
CREATE INDEX "lemon_squeezy_license_keys_order_id_index" on "lemon_squeezy_license_keys" ("order_id");
CREATE INDEX "lemon_squeezy_license_keys_product_id_index" on "lemon_squeezy_license_keys" ("product_id");
CREATE TABLE IF NOT EXISTS "lemon_squeezy_license_key_instances" ("id" integer primary key autoincrement not null, "identifier" varchar not null, "license_key_id" varchar not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "lemon_squeezy_license_key_instances_identifier_unique" on "lemon_squeezy_license_key_instances" ("identifier");
CREATE TABLE IF NOT EXISTS "referrals" ("id" integer primary key autoincrement not null, "user_id" integer not null, "referral_code" varchar not null, "referrer_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("referrer_id") references "users"("id") on delete set null);
CREATE UNIQUE INDEX "referrals_referral_code_unique" on "referrals" ("referral_code");
CREATE TABLE IF NOT EXISTS "permissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "permissions_name_guard_name_unique" on "permissions" ("name", "guard_name");
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "organization_id" integer, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime, "label" varchar);
CREATE INDEX "roles_team_foreign_key_index" on "roles" ("organization_id");
CREATE UNIQUE INDEX "roles_organization_id_name_guard_name_unique" on "roles" ("organization_id", "name", "guard_name");
CREATE TABLE IF NOT EXISTS "model_has_permissions" ("permission_id" integer not null, "model_type" varchar not null, "model_id" integer not null, "organization_id" integer not null, foreign key("permission_id") references "permissions"("id") on delete cascade, primary key ("organization_id", "permission_id", "model_id", "model_type"));
CREATE INDEX "model_has_permissions_model_id_model_type_index" on "model_has_permissions" ("model_id", "model_type");
CREATE INDEX "model_has_permissions_team_foreign_key_index" on "model_has_permissions" ("organization_id");
CREATE TABLE IF NOT EXISTS "model_has_roles" ("role_id" integer not null, "model_type" varchar not null, "model_id" integer not null, "organization_id" integer not null, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("organization_id", "role_id", "model_id", "model_type"));
CREATE INDEX "model_has_roles_model_id_model_type_index" on "model_has_roles" ("model_id", "model_type");
CREATE INDEX "model_has_roles_team_foreign_key_index" on "model_has_roles" ("organization_id");
CREATE TABLE IF NOT EXISTS "role_has_permissions" ("permission_id" integer not null, "role_id" integer not null, foreign key("permission_id") references "permissions"("id") on delete cascade, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("permission_id", "role_id"));
CREATE TABLE IF NOT EXISTS "notifications" ("id" varchar not null, "type" varchar not null, "notifiable_type" varchar not null, "notifiable_id" integer not null, "data" text not null, "read_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE INDEX "notifications_notifiable_type_notifiable_id_index" on "notifications" ("notifiable_type", "notifiable_id");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" text not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_expires_at_index" on "personal_access_tokens" ("expires_at");
CREATE TABLE IF NOT EXISTS "activity_log" ("id" integer primary key autoincrement not null, "log_name" varchar, "description" text not null, "subject_type" varchar, "subject_id" integer, "causer_type" varchar, "causer_id" integer, "properties" text, "created_at" datetime, "updated_at" datetime, "event" varchar, "batch_uuid" varchar);
CREATE INDEX "subject" on "activity_log" ("subject_type", "subject_id");
CREATE INDEX "causer" on "activity_log" ("causer_type", "causer_id");
CREATE INDEX "activity_log_log_name_index" on "activity_log" ("log_name");
CREATE TABLE IF NOT EXISTS "agent_conversations" ("id" varchar not null, "user_id" integer not null, "title" varchar not null, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE INDEX "agent_conversations_user_id_updated_at_index" on "agent_conversations" ("user_id", "updated_at");
CREATE TABLE IF NOT EXISTS "agent_conversation_messages" ("id" varchar not null, "conversation_id" varchar not null, "user_id" integer not null, "agent" varchar not null, "role" varchar not null, "content" text not null, "attachments" text not null, "tool_calls" text not null, "tool_results" text not null, "usage" text not null, "meta" text not null, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE INDEX "conversation_index" on "agent_conversation_messages" ("conversation_id", "user_id", "updated_at");
CREATE INDEX "agent_conversation_messages_user_id_index" on "agent_conversation_messages" ("user_id");
CREATE INDEX "agent_conversation_messages_conversation_id_index" on "agent_conversation_messages" ("conversation_id");
CREATE TABLE IF NOT EXISTS "media" ("id" integer primary key autoincrement not null, "model_type" varchar not null, "model_id" integer not null, "uuid" varchar, "collection_name" varchar not null, "name" varchar not null, "file_name" varchar not null, "mime_type" varchar, "disk" varchar not null, "conversions_disk" varchar, "size" integer not null, "manipulations" text not null, "custom_properties" text not null, "generated_conversions" text not null, "responsive_images" text not null, "order_column" integer, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "media_model_type_model_id_index" on "media" ("model_type", "model_id");
CREATE UNIQUE INDEX "media_uuid_unique" on "media" ("uuid");
CREATE INDEX "media_order_column_index" on "media" ("order_column");
CREATE TABLE IF NOT EXISTS "model_flags" ("id" integer primary key autoincrement not null, "name" varchar not null, "flaggable_type" varchar not null, "flaggable_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "model_flags_flaggable_type_flaggable_id_index" on "model_flags" ("flaggable_type", "flaggable_id");
CREATE INDEX "model_flags_name_flaggable_id_flaggable_type_index" on "model_flags" ("name", "flaggable_id", "flaggable_type");
CREATE TABLE IF NOT EXISTS "features" ("id" integer primary key autoincrement not null, "name" varchar not null, "scope" varchar not null, "value" text not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "features_name_scope_unique" on "features" ("name", "scope");
CREATE TABLE IF NOT EXISTS "feature_segments" ("id" integer primary key autoincrement not null, "feature" varchar not null, "scope" varchar not null, "values" text not null, "active" tinyint(1) not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "feature_segments_feature_scope_active_unique" on "feature_segments" ("feature", "scope", "active");
CREATE TABLE IF NOT EXISTS "tags" ("id" integer primary key autoincrement not null, "name" text not null, "slug" text not null, "type" varchar, "order_column" integer, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "taggables" ("tag_id" integer not null, "taggable_type" varchar not null, "taggable_id" integer not null, foreign key("tag_id") references "tags"("id") on delete cascade);
CREATE INDEX "taggables_taggable_type_taggable_id_index" on "taggables" ("taggable_type", "taggable_id");
CREATE UNIQUE INDEX "taggables_tag_id_taggable_id_taggable_type_unique" on "taggables" ("tag_id", "taggable_id", "taggable_type");
CREATE TABLE IF NOT EXISTS "flags" ("id" integer primary key autoincrement not null, "name" varchar not null, "flaggable_type" varchar not null, "flaggable_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "flags_flaggable_type_flaggable_id_index" on "flags" ("flaggable_type", "flaggable_id");
CREATE INDEX "flags_name_flaggable_id_flaggable_type_index" on "flags" ("name", "flaggable_id", "flaggable_type");
CREATE TABLE IF NOT EXISTS "imports" ("id" integer primary key autoincrement not null, "completed_at" datetime, "file_name" varchar not null, "file_path" varchar not null, "importer" varchar not null, "processed_rows" integer not null default '0', "total_rows" integer not null, "successful_rows" integer not null default '0', "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "exports" ("id" integer primary key autoincrement not null, "completed_at" datetime, "file_disk" varchar not null, "file_name" varchar, "exporter" varchar not null, "processed_rows" integer not null default '0', "total_rows" integer not null, "successful_rows" integer not null default '0', "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "failed_import_rows" ("id" integer primary key autoincrement not null, "data" text not null, "import_id" integer not null, "validation_error" text, "created_at" datetime, "updated_at" datetime, foreign key("import_id") references "imports"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "categoryables" ("category_id" integer not null, "categoryable_type" varchar not null, "categoryable_id" integer not null, foreign key("category_id") references "categories"("id") on delete cascade, primary key ("category_id", "categoryable_type", "categoryable_id"));
CREATE TABLE IF NOT EXISTS "levels" ("id" integer primary key autoincrement not null, "level" integer not null, "next_level_experience" integer, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "levels_level_unique" on "levels" ("level");
CREATE INDEX "levels_next_level_experience_index" on "levels" ("next_level_experience");
CREATE TABLE IF NOT EXISTS "experiences" ("id" integer primary key autoincrement not null, "user_id" integer not null, "level_id" integer not null, "experience_points" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("level_id") references "levels"("id"));
CREATE INDEX "experiences_experience_points_index" on "experiences" ("experience_points");
CREATE TABLE IF NOT EXISTS "experience_audits" ("id" integer primary key autoincrement not null, "user_id" integer not null, "points" integer not null, "levelled_up" tinyint(1) not null default '0', "level_to" integer, "type" varchar check ("type" in ('add', 'remove', 'reset', 'level_up')) not null, "reason" varchar, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"));
CREATE INDEX "experience_audits_points_index" on "experience_audits" ("points");
CREATE TABLE IF NOT EXISTS "achievements" ("id" integer primary key autoincrement not null, "name" varchar not null, "is_secret" tinyint(1) not null default '0', "description" text, "image" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "achievement_user" ("id" integer primary key autoincrement not null, "user_id" integer not null, "achievement_id" integer not null, "progress" integer, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id"), foreign key("achievement_id") references "achievements"("id"));
CREATE INDEX "achievement_user_progress_index" on "achievement_user" ("progress");
CREATE TABLE IF NOT EXISTS "streak_activities" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "streak_activities_name_unique" on "streak_activities" ("name");
CREATE TABLE IF NOT EXISTS "streaks" ("id" integer primary key autoincrement not null, "user_id" integer not null, "activity_id" integer not null, "count" integer not null default '1', "activity_at" datetime not null, "created_at" datetime, "updated_at" datetime, "frozen_until" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("activity_id") references "streak_activities"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "streak_histories" ("id" integer primary key autoincrement not null, "user_id" integer not null, "activity_id" integer not null, "count" integer not null default '1', "started_at" datetime not null, "ended_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("activity_id") references "streak_activities"("id"));
CREATE TABLE IF NOT EXISTS "organizations" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "settings" text, "owner_id" integer, "created_at" datetime, "updated_at" datetime, "created_by" integer, "updated_by" integer, "deleted_at" datetime, "deleted_by" integer, "billing_email" varchar, "tax_id" varchar, "billing_address" text, "stripe_customer_id" varchar, "paddle_customer_id" varchar, "extra_attributes" text, foreign key("owner_id") references "users"("id") on delete set null, foreign key("created_by") references "users"("id") on delete set null, foreign key("updated_by") references "users"("id") on delete set null, foreign key("deleted_by") references "users"("id") on delete set null);
CREATE INDEX "organizations_name_index" on "organizations" ("name");
CREATE UNIQUE INDEX "organizations_slug_unique" on "organizations" ("slug");
CREATE TABLE IF NOT EXISTS "organization_invitations" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "email" varchar not null, "role" varchar not null default 'member', "status" varchar not null default 'pending', "token" varchar not null, "invited_by" integer not null, "expires_at" datetime not null, "accepted_at" datetime, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade, foreign key("invited_by") references "users"("id") on delete cascade);
CREATE INDEX "organization_invitations_organization_id_email_index" on "organization_invitations" ("organization_id", "email");
CREATE INDEX "organization_invitations_email_index" on "organization_invitations" ("email");
CREATE INDEX "organization_invitations_status_index" on "organization_invitations" ("status");
CREATE UNIQUE INDEX "organization_invitations_token_unique" on "organization_invitations" ("token");
CREATE TABLE IF NOT EXISTS "organization_user" ("organization_id" integer not null, "user_id" integer not null, "is_default" tinyint(1) not null default '0', "joined_at" datetime not null default CURRENT_TIMESTAMP, "invited_by" integer, "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade, foreign key("invited_by") references "users"("id") on delete set null, primary key ("organization_id", "user_id"));
CREATE INDEX "organization_user_user_id_index" on "organization_user" ("user_id");
CREATE UNIQUE INDEX organization_user_unique_default ON organization_user(user_id) WHERE is_default = 1;
CREATE TABLE IF NOT EXISTS "posts" ("id" integer primary key autoincrement not null, "author_id" integer not null, "title" varchar not null, "slug" varchar not null, "excerpt" text, "content" text not null, "is_published" tinyint(1) not null default ('0'), "published_at" datetime, "meta_title" varchar, "meta_description" text, "meta_keywords" varchar, "views" integer not null default ('0'), "created_by" integer, "updated_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "organization_id" integer, foreign key("updated_by") references users("id") on delete set null on update no action, foreign key("created_by") references users("id") on delete set null on update no action, foreign key("author_id") references users("id") on delete cascade on update no action, foreign key("organization_id") references "organizations"("id") on delete set null);
CREATE INDEX "posts_is_published_index" on "posts" ("is_published");
CREATE INDEX "posts_published_at_index" on "posts" ("published_at");
CREATE INDEX "posts_slug_index" on "posts" ("slug");
CREATE UNIQUE INDEX "posts_slug_unique" on "posts" ("slug");
CREATE INDEX "posts_organization_id_index" on "posts" ("organization_id");
CREATE TABLE IF NOT EXISTS "help_articles" ("id" integer primary key autoincrement not null, "title" varchar not null, "slug" varchar not null, "excerpt" text, "content" text not null, "category" varchar, "views" integer not null default ('0'), "helpful_count" integer not null default ('0'), "not_helpful_count" integer not null default ('0'), "order" integer not null default ('0'), "is_published" tinyint(1) not null default ('0'), "created_by" integer, "updated_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "organization_id" integer, foreign key("updated_by") references users("id") on delete set null on update no action, foreign key("created_by") references users("id") on delete set null on update no action, foreign key("organization_id") references "organizations"("id") on delete set null);
CREATE INDEX "help_articles_category_index" on "help_articles" ("category");
CREATE INDEX "help_articles_is_published_index" on "help_articles" ("is_published");
CREATE INDEX "help_articles_slug_index" on "help_articles" ("slug");
CREATE UNIQUE INDEX "help_articles_slug_unique" on "help_articles" ("slug");
CREATE INDEX "help_articles_organization_id_index" on "help_articles" ("organization_id");
CREATE TABLE IF NOT EXISTS "changelog_entries" ("id" integer primary key autoincrement not null, "title" varchar not null, "description" text not null, "version" varchar, "type" varchar not null default ('added'), "is_published" tinyint(1) not null default ('0'), "released_at" datetime, "created_by" integer, "updated_by" integer, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "organization_id" integer, foreign key("updated_by") references users("id") on delete set null on update no action, foreign key("created_by") references users("id") on delete set null on update no action, foreign key("organization_id") references "organizations"("id") on delete set null);
CREATE INDEX "changelog_entries_is_published_index" on "changelog_entries" ("is_published");
CREATE INDEX "changelog_entries_released_at_index" on "changelog_entries" ("released_at");
CREATE INDEX "changelog_entries_type_index" on "changelog_entries" ("type");
CREATE INDEX "changelog_entries_organization_id_index" on "changelog_entries" ("organization_id");
CREATE TABLE IF NOT EXISTS "contact_submissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "subject" varchar not null, "message" text not null, "status" varchar default ('new'), "created_at" datetime, "updated_at" datetime, "created_by" integer, "updated_by" integer, "organization_id" integer, foreign key("updated_by") references users("id") on delete set null on update no action, foreign key("created_by") references users("id") on delete set null on update no action, foreign key("organization_id") references "organizations"("id") on delete set null);
CREATE INDEX "contact_submissions_organization_id_index" on "contact_submissions" ("organization_id");
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "type" varchar not null default ('default'), "_lft" integer not null default ('0'), "_rgt" integer not null default ('0'), "parent_id" integer, "created_at" datetime, "updated_at" datetime, "organization_id" integer, foreign key("organization_id") references "organizations"("id") on delete set null);
CREATE INDEX "categories__lft__rgt_parent_id_index" on "categories" ("_lft", "_rgt", "parent_id");
CREATE INDEX "categories_organization_id_index" on "categories" ("organization_id");
CREATE TABLE IF NOT EXISTS "plans" ("id" integer primary key autoincrement not null, "name" text not null, "slug" varchar not null, "description" text, "is_active" tinyint(1) not null default '1', "price" numeric not null default '0.00', "signup_fee" numeric not null default '0.00', "currency" varchar not null, "trial_period" integer not null default '0', "trial_interval" varchar not null default 'day', "invoice_period" integer not null default '0', "invoice_interval" varchar not null default 'month', "grace_period" integer not null default '0', "grace_interval" varchar not null default 'day', "prorate_day" integer, "prorate_period" integer, "prorate_extend_due" integer, "active_subscribers_limit" integer, "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "is_per_seat" tinyint(1) not null default '0', "price_per_seat" numeric not null default '0.00');
CREATE UNIQUE INDEX "plans_slug_unique" on "plans" ("slug");
CREATE TABLE IF NOT EXISTS "plan_features" ("id" integer primary key autoincrement not null, "plan_id" integer not null, "name" text not null, "slug" varchar not null, "description" text, "value" varchar not null, "resettable_period" integer not null default '0', "resettable_interval" varchar not null default 'month', "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE TABLE IF NOT EXISTS "plan_subscriptions" ("id" integer primary key autoincrement not null, "subscriber_type" varchar not null, "subscriber_id" integer not null, "plan_id" integer not null, "name" text not null, "slug" varchar not null, "description" text, "timezone" varchar, "trial_ends_at" datetime, "starts_at" datetime, "ends_at" datetime, "canceled_at" datetime, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, "gateway_subscription_id" varchar, "quantity" integer not null default '1');
CREATE INDEX "plan_subscriptions_subscriber_type_subscriber_id_index" on "plan_subscriptions" ("subscriber_type", "subscriber_id");
CREATE TABLE IF NOT EXISTS "plan_subscription_usage" ("id" integer primary key autoincrement not null, "subscription_id" integer not null, "feature_id" integer not null, "used" integer not null, "timezone" varchar, "valid_until" datetime, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE UNIQUE INDEX "plan_features_plan_id_slug_unique" on "plan_features" ("plan_id", "slug");
CREATE TABLE IF NOT EXISTS "credits" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "creditable_type" varchar not null, "creditable_id" integer not null, "amount" integer not null, "running_balance" integer not null, "type" varchar not null, "description" varchar, "metadata" text, "expires_at" datetime, "created_at" datetime, "updated_at" datetime, "extra_attributes" text, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE INDEX "credits_creditable_type_creditable_id_index" on "credits" ("creditable_type", "creditable_id");
CREATE TABLE IF NOT EXISTS "credit_packs" ("id" integer primary key autoincrement not null, "name" varchar not null, "slug" varchar not null, "description" text, "credits" integer not null, "bonus_credits" integer not null default '0', "price" integer not null, "currency" varchar not null default 'usd', "validity_days" integer, "is_active" tinyint(1) not null default '1', "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE UNIQUE INDEX "credit_packs_slug_unique" on "credit_packs" ("slug");
CREATE TABLE IF NOT EXISTS "payment_gateways" ("id" integer primary key autoincrement not null, "name" varchar not null, "type" varchar not null, "settings" text, "is_active" tinyint(1) not null default '1', "is_default" tinyint(1) not null default '0', "supported_currencies" text, "supported_payment_methods" text, "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gateway_products" ("id" integer primary key autoincrement not null, "payment_gateway_id" integer not null, "plan_id" integer not null, "gateway_product_id" varchar not null, "gateway_price_id" varchar, "created_at" datetime, "updated_at" datetime, foreign key("payment_gateway_id") references "payment_gateways"("id") on delete cascade, foreign key("plan_id") references "plans"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "refund_requests" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "invoice_id" integer not null, "amount" integer not null, "reason" text, "status" varchar not null default 'pending', "processed_at" datetime, "processed_by" integer, "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade, foreign key("invoice_id") references "invoices"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "billing_metrics" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "date" date not null, "mrr" integer not null default '0', "arr" integer not null default '0', "new_subscriptions" integer not null default '0', "churned" integer not null default '0', "credits_purchased" integer not null default '0', "credits_used" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "invoices" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "billable_type" varchar not null, "billable_id" integer not null, "number" varchar not null, "status" varchar not null default ('draft'), "currency" varchar not null default ('usd'), "subtotal" integer not null, "tax" integer not null default ('0'), "total" integer not null, "paid_at" datetime, "due_date" date, "line_items" text, "billing_address" text, "payment_gateway_id" integer, "gateway_invoice_id" varchar, "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references organizations("id") on delete cascade on update no action, foreign key("payment_gateway_id") references "payment_gateways"("id") on delete set null);
CREATE INDEX "invoices_billable_type_billable_id_index" on "invoices" ("billable_type", "billable_id");
CREATE UNIQUE INDEX "invoices_number_unique" on "invoices" ("number");
CREATE TABLE IF NOT EXISTS "organization_domains" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "domain" varchar not null, "type" varchar check ("type" in ('subdomain', 'custom')) not null, "is_verified" tinyint(1) not null default '0', "verification_token" varchar, "is_primary" tinyint(1) not null default '0', "verified_at" datetime, "created_at" datetime, "updated_at" datetime, "status" varchar check ("status" in ('pending_dns', 'dns_verified', 'ssl_provisioning', 'active', 'error', 'expired')) not null default 'pending_dns', "cname_target" varchar, "failure_reason" varchar, "dns_check_attempts" integer not null default '0', "last_dns_check_at" datetime, "ssl_issued_at" datetime, "ssl_expires_at" datetime, "deleted_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE UNIQUE INDEX "organization_domains_domain_unique" on "organization_domains" ("domain");
CREATE TABLE IF NOT EXISTS "webhook_logs" ("id" integer primary key autoincrement not null, "gateway" varchar not null, "event_type" varchar not null, "payload" text, "processed" tinyint(1) not null default ('0'), "response" text, "created_at" datetime, "updated_at" datetime, "organization_id" integer, foreign key("organization_id") references "organizations"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "terms_versions" ("id" integer primary key autoincrement not null, "title" varchar not null, "slug" varchar not null, "body" text not null, "type" varchar not null, "effective_at" date not null, "summary" text, "is_required" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "terms_versions_slug_unique" on "terms_versions" ("slug");
CREATE TABLE IF NOT EXISTS "user_terms_acceptances" ("id" integer primary key autoincrement not null, "user_id" integer not null, "terms_version_id" integer not null, "accepted_at" datetime not null, "ip" varchar, "user_agent" text, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id") on delete cascade, foreign key("terms_version_id") references "terms_versions"("id") on delete cascade);
CREATE UNIQUE INDEX "user_terms_acceptances_user_id_terms_version_id_unique" on "user_terms_acceptances" ("user_id", "terms_version_id");
CREATE TABLE IF NOT EXISTS "enterprise_inquiries" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "company" varchar, "phone" varchar, "message" text not null, "status" varchar not null default 'new', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "voucher_scopes" ("id" integer primary key autoincrement not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "vouchers" ("id" integer primary key autoincrement not null, "code" varchar not null, "model_type" varchar not null, "model_id" integer not null, "data" text, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "vouchers_model_type_model_id_index" on "vouchers" ("model_type", "model_id");
CREATE UNIQUE INDEX "vouchers_code_unique" on "vouchers" ("code");
CREATE TABLE IF NOT EXISTS "user_voucher" ("id" integer primary key autoincrement not null, "user_id" integer not null, "voucher_id" integer not null, "redeemed_at" datetime not null, foreign key("user_id") references "users"("id"), foreign key("voucher_id") references "vouchers"("id"));
CREATE TABLE IF NOT EXISTS "failed_payment_attempts" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "gateway" varchar not null, "gateway_subscription_id" varchar, "attempt_number" integer not null default '1', "dunning_emails_sent" integer not null default '0', "failed_at" datetime not null, "last_dunning_sent_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE INDEX "failed_payment_attempts_organization_id_failed_at_index" on "failed_payment_attempts" ("organization_id", "failed_at");
CREATE TABLE IF NOT EXISTS "affiliates" ("id" integer primary key autoincrement not null, "user_id" integer not null, "affiliate_code" varchar not null, "status" varchar not null default 'pending', "commission_rate" numeric not null default '20', "payment_email" varchar, "payment_method" varchar not null default 'paypal', "payment_details" text, "total_earnings" integer not null default '0', "pending_earnings" integer not null default '0', "paid_earnings" integer not null default '0', "total_referrals" integer not null default '0', "successful_conversions" integer not null default '0', "admin_notes" text, "approved_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE INDEX "affiliates_affiliate_code_index" on "affiliates" ("affiliate_code");
CREATE INDEX "affiliates_status_index" on "affiliates" ("status");
CREATE UNIQUE INDEX "affiliates_affiliate_code_unique" on "affiliates" ("affiliate_code");
CREATE TABLE IF NOT EXISTS "affiliate_commissions" ("id" integer primary key autoincrement not null, "affiliate_id" integer not null, "referred_organization_id" integer, "invoice_id" integer, "amount" integer not null, "currency" varchar not null default 'USD', "status" varchar not null default 'pending', "description" text, "approved_at" datetime, "paid_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("affiliate_id") references "affiliates"("id") on delete cascade, foreign key("referred_organization_id") references "organizations"("id") on delete set null, foreign key("invoice_id") references "invoices"("id") on delete set null);
CREATE INDEX "affiliate_commissions_affiliate_id_status_index" on "affiliate_commissions" ("affiliate_id", "status");
CREATE TABLE IF NOT EXISTS "affiliate_payouts" ("id" integer primary key autoincrement not null, "affiliate_id" integer not null, "amount" integer not null, "currency" varchar not null default 'USD', "status" varchar not null default 'pending', "payment_method" varchar not null, "transaction_id" varchar, "notes" text, "processed_by" integer, "processed_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("affiliate_id") references "affiliates"("id") on delete cascade, foreign key("processed_by") references "users"("id") on delete set null);
CREATE INDEX "affiliate_payouts_affiliate_id_status_index" on "affiliate_payouts" ("affiliate_id", "status");
CREATE TABLE IF NOT EXISTS "pan_analytics" ("id" integer primary key autoincrement not null, "name" varchar not null, "impressions" integer not null default '0', "hovers" integer not null default '0', "clicks" integer not null default '0');
CREATE TABLE IF NOT EXISTS "mail_templates" ("id" integer primary key autoincrement not null, "event" varchar not null, "name" varchar not null, "subject" varchar not null, "body" text not null, "meta" text, "recipients" text not null, "attachments" text not null, "delay" varchar, "is_active" tinyint(1) not null, "created_at" datetime, "updated_at" datetime, "from_name" varchar, "from_email" varchar);
CREATE INDEX "mail_templates_event_index" on "mail_templates" ("event");
CREATE TABLE IF NOT EXISTS "mail_exceptions" ("id" integer primary key autoincrement not null, "mail_template_id" integer not null, "data" text not null, "type" varchar not null, "code" varchar not null, "message" text not null, "file" varchar not null, "line" integer not null, "preview" text not null, "trace" text not null, "created_at" datetime, "updated_at" datetime, foreign key("mail_template_id") references "mail_templates"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "shareables" ("id" integer primary key autoincrement not null, "shareable_type" varchar not null, "shareable_id" integer not null, "target_type" varchar not null, "target_id" integer not null, "permission" varchar not null default 'view', "shared_by" integer not null, "expires_at" datetime, "created_at" datetime, "updated_at" datetime, foreign key("shared_by") references "users"("id") on delete cascade);
CREATE INDEX "shareables_shareable_type_shareable_id_index" on "shareables" ("shareable_type", "shareable_id");
CREATE INDEX "shareables_target_type_target_id_index" on "shareables" ("target_type", "target_id");
CREATE UNIQUE INDEX "shareables_unique_share" on "shareables" ("shareable_type", "shareable_id", "target_type", "target_id");
CREATE TABLE IF NOT EXISTS "visibility_demos" ("id" integer primary key autoincrement not null, "created_at" datetime, "updated_at" datetime, "organization_id" integer, "visibility" varchar not null default 'organization', "cloned_from" integer, "title" varchar not null, foreign key("organization_id") references "organizations"("id") on delete set null);
CREATE INDEX "visibility_demos_organization_id_visibility_index" on "visibility_demos" ("organization_id", "visibility");
CREATE TABLE IF NOT EXISTS "organization_settings" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "group" varchar not null, "name" varchar not null, "payload" text not null, "is_encrypted" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE UNIQUE INDEX "organization_settings_organization_id_group_name_unique" on "organization_settings" ("organization_id", "group", "name");
CREATE TABLE IF NOT EXISTS "pages" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "name" varchar not null, "slug" varchar not null, "puck_json" text, "is_published" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "meta_description" varchar, "meta_image" varchar, "extra_attributes" text, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE UNIQUE INDEX "pages_organization_id_slug_unique" on "pages" ("organization_id", "slug");
CREATE TABLE IF NOT EXISTS "page_revisions" ("id" integer primary key autoincrement not null, "page_id" integer not null, "puck_json" text, "name" varchar, "slug" varchar, "is_published" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("page_id") references "pages"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" integer primary key autoincrement not null, "organization_id" integer, "actor_id" integer, "actor_type" varchar not null default 'user', "action" varchar not null, "subject_type" varchar, "subject_id" varchar, "old_value" text, "new_value" text, "ip_address" varchar, "created_at" datetime not null default CURRENT_TIMESTAMP, foreign key("organization_id") references "organizations"("id") on delete set null, foreign key("actor_id") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "slug_redirects" ("id" integer primary key autoincrement not null, "old_slug" varchar not null, "organization_id" integer not null, "redirects_to_slug" varchar not null, "created_at" datetime not null default CURRENT_TIMESTAMP, "expires_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE UNIQUE INDEX "slug_redirects_old_slug_unique" on "slug_redirects" ("old_slug");
CREATE TABLE IF NOT EXISTS "social_accounts" ("id" integer primary key autoincrement not null, "user_id" integer not null, "provider" varchar not null, "provider_id" varchar not null, "token" varchar, "refresh_token" varchar, "token_expires_at" datetime, "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE UNIQUE INDEX "social_accounts_provider_provider_id_unique" on "social_accounts" ("provider", "provider_id");
CREATE INDEX "social_accounts_user_id_provider_index" on "social_accounts" ("user_id", "provider");
CREATE TABLE IF NOT EXISTS "notification_preferences" ("id" integer primary key autoincrement not null, "user_id" integer not null, "notification_type" varchar not null, "via_database" tinyint(1) not null default '1', "via_email" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE UNIQUE INDEX "notification_preferences_user_id_notification_type_unique" on "notification_preferences" ("user_id", "notification_type");
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar, "two_factor_secret" text, "two_factor_recovery_codes" text, "two_factor_confirmed_at" datetime, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "current_team_id" integer, "onboarding_completed" tinyint(1) not null default ('0'), "timezone" varchar, "deleted_at" datetime, "theme_mode" varchar not null default ('system'), "phone" varchar, "color" varchar, "tags" text, "position" integer, foreign key("current_team_id") references governor_teams("id") on delete cascade on update cascade);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "mail_attachments" ("id" integer primary key autoincrement not null, "mail_id" integer not null, "disk" varchar not null, "uuid" varchar not null, "filename" varchar not null, "mime" varchar not null, "inline" tinyint(1) not null, "size" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("mail_id") references "mails"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "mailables" ("id" integer primary key autoincrement not null, "mail_id" integer not null, "mailable_type" varchar not null, "mailable_id" integer not null, foreign key("mail_id") references "mails"("id") on delete cascade);
CREATE INDEX "mailables_mailable_type_mailable_id_index" on "mailables" ("mailable_type", "mailable_id");
CREATE TABLE IF NOT EXISTS "mails" ("id" integer primary key autoincrement not null, "uuid" varchar, "mail_class" varchar, "subject" varchar, "from" text, "reply_to" text, "to" text, "cc" text, "bcc" text, "html" text, "text" text, "opens" integer not null default ('0'), "clicks" integer not null default ('0'), "sent_at" datetime, "resent_at" datetime, "accepted_at" datetime, "delivered_at" datetime, "last_opened_at" datetime, "last_clicked_at" datetime, "complained_at" datetime, "soft_bounced_at" datetime, "hard_bounced_at" datetime, "unsubscribed_at" datetime, "created_at" datetime, "updated_at" datetime, "mailer" varchar not null, "stream_id" varchar, "tags" text, "transport" varchar);
CREATE INDEX "mails_mail_class_index" on "mails" ("mail_class");
CREATE INDEX "mails_uuid_index" on "mails" ("uuid");
CREATE TABLE IF NOT EXISTS "mail_events" ("id" integer primary key autoincrement not null, "mail_id" integer not null, "type" varchar not null, "ip_address" varchar, "hostname" varchar, "platform" varchar, "os" varchar, "browser" varchar, "user_agent" varchar, "city" varchar, "country_code" varchar, "link" text, "tag" varchar, "payload" text, "created_at" datetime, "updated_at" datetime, "occurred_at" datetime, "unsuppressed_at" datetime, foreign key("mail_id") references mails("id") on delete cascade on update no action);
CREATE TABLE IF NOT EXISTS "announcements" ("id" integer primary key autoincrement not null, "title" varchar not null, "body" text not null, "level" varchar not null default ('info'), "scope" varchar not null default ('global'), "organization_id" integer, "starts_at" datetime, "ends_at" datetime, "is_active" tinyint(1) not null default ('1'), "created_by" integer, "created_at" datetime, "updated_at" datetime, "governor_owned_by" integer, "position" integer, foreign key("created_by") references users("id") on delete set null on update no action, foreign key("organization_id") references organizations("id") on delete set null on update no action, foreign key("governor_owned_by") references "users"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "webhook_calls" ("id" integer primary key autoincrement not null, "name" varchar not null, "url" varchar not null, "headers" text, "payload" text, "exception" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "health_check_result_history_items" ("id" integer primary key autoincrement not null, "check_name" varchar not null, "check_label" varchar not null, "status" varchar not null, "notification_message" text, "short_summary" varchar, "meta" text not null, "ended_at" datetime not null, "batch" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "health_check_result_history_items_created_at_index" on "health_check_result_history_items" ("created_at");
CREATE INDEX "health_check_result_history_items_batch_index" on "health_check_result_history_items" ("batch");
CREATE TABLE IF NOT EXISTS "pulse_values" ("id" integer primary key autoincrement not null, "timestamp" integer not null, "type" varchar not null, "key" text not null, "key_hash" varchar not null, "value" text not null);
CREATE INDEX "pulse_values_timestamp_index" on "pulse_values" ("timestamp");
CREATE INDEX "pulse_values_type_index" on "pulse_values" ("type");
CREATE UNIQUE INDEX "pulse_values_type_key_hash_unique" on "pulse_values" ("type", "key_hash");
CREATE TABLE IF NOT EXISTS "pulse_entries" ("id" integer primary key autoincrement not null, "timestamp" integer not null, "type" varchar not null, "key" text not null, "key_hash" varchar not null, "value" integer);
CREATE INDEX "pulse_entries_timestamp_index" on "pulse_entries" ("timestamp");
CREATE INDEX "pulse_entries_type_index" on "pulse_entries" ("type");
CREATE INDEX "pulse_entries_key_hash_index" on "pulse_entries" ("key_hash");
CREATE INDEX "pulse_entries_timestamp_type_key_hash_value_index" on "pulse_entries" ("timestamp", "type", "key_hash", "value");
CREATE TABLE IF NOT EXISTS "pulse_aggregates" ("id" integer primary key autoincrement not null, "bucket" integer not null, "period" integer not null, "type" varchar not null, "key" text not null, "key_hash" varchar not null, "aggregate" varchar not null, "value" numeric not null, "count" integer);
CREATE UNIQUE INDEX "pulse_aggregates_bucket_period_type_aggregate_key_hash_unique" on "pulse_aggregates" ("bucket", "period", "type", "aggregate", "key_hash");
CREATE INDEX "pulse_aggregates_period_bucket_index" on "pulse_aggregates" ("period", "bucket");
CREATE INDEX "pulse_aggregates_type_index" on "pulse_aggregates" ("type");
CREATE INDEX "pulse_aggregates_period_type_aggregate_bucket_index" on "pulse_aggregates" ("period", "type", "aggregate", "bucket");
CREATE TABLE IF NOT EXISTS "reports" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "name" varchar not null, "puck_json" text, "schedule" varchar, "output_format" varchar not null default 'pdf', "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE INDEX "reports_organization_id_index" on "reports" ("organization_id");
CREATE TABLE IF NOT EXISTS "dashboards" ("id" integer primary key autoincrement not null, "organization_id" integer not null, "name" varchar not null, "puck_json" text, "is_default" tinyint(1) not null default '0', "refresh_interval" integer, "created_at" datetime, "updated_at" datetime, foreign key("organization_id") references "organizations"("id") on delete cascade);
CREATE INDEX "dashboards_organization_id_index" on "dashboards" ("organization_id");
CREATE TABLE IF NOT EXISTS "report_outputs" ("id" integer primary key autoincrement not null, "report_id" integer not null, "format" varchar not null, "disk" varchar not null default 'local', "path" varchar not null, "size_bytes" integer not null default '0', "is_scheduled" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("report_id") references "reports"("id") on delete cascade);
CREATE INDEX "report_outputs_report_id_index" on "report_outputs" ("report_id");
CREATE TABLE IF NOT EXISTS "data_table_audit_log" ("id" integer primary key autoincrement not null, "table_name" varchar not null, "action" varchar not null, "row_id" varchar, "column" varchar, "old_value" text, "new_value" text, "user_id" integer, "ip_address" varchar, "created_at" datetime, foreign key("user_id") references "users"("id") on delete set null);
CREATE INDEX "data_table_audit_log_table_name_created_at_index" on "data_table_audit_log" ("table_name", "created_at");
CREATE INDEX "data_table_audit_log_table_name_row_id_index" on "data_table_audit_log" ("table_name", "row_id");
CREATE TABLE IF NOT EXISTS "data_table_saved_views" ("id" integer primary key autoincrement not null, "user_id" integer not null, "table_name" varchar not null, "name" varchar not null, "filters" text, "sort" varchar, "columns" text, "column_order" text, "is_default" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE INDEX "data_table_saved_views_user_id_table_name_index" on "data_table_saved_views" ("user_id", "table_name");
INSERT INTO migrations (migration, batch) VALUES ('0001_01_01_000000_create_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_01_000001_create_cache_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_01_000002_create_jobs_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000001_create_governor_roles_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000002_create_governor_groups_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000003_create_governor_entities_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000004_create_governor_actions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000005_create_governor_ownerships_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000006_create_governor_role_user_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000007_create_governor_teams_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000008_create_governor_team_user_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000009_create_governor_team_invitations_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000010_create_governor_teamables_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('0001_01_02_000011_create_governor_permissions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2019_02_25_231036_create_scheduled_notifications_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2021_09_10_130000_add_meta_to_scheduled_notifications', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_01_01_000000_create_workflows_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_01_01_000001_create_workflow_logs_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_01_01_000002_create_workflow_signals_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_01_01_000003_create_workflow_timers_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_01_01_000004_create_workflow_exceptions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_01_01_000005_create_workflow_relationships_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_08_03_000000_create_vector_extension', 1);
INSERT INTO migrations (migration, batch) VALUES ('2022_12_14_083707_create_settings_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2023_01_16_000001_create_customers_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2023_01_16_000002_create_subscriptions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2023_01_16_000003_create_orders_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2023_01_16_000004_create_license_keys_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2023_01_16_000005_create_license_key_instances_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2023_05_28_135232_create_referrals_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_01_29_041033_create_permission_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_01_29_055958_create_notifications_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_01_29_121401_create_embedding_demos_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_05_125308_create_personal_access_tokens_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_05_161850_create_activity_log_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_05_161851_add_event_column_to_activity_log_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_05_161852_add_batch_uuid_column_to_activity_log_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_06_081136_create_agent_conversations_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_06_152347_create_media_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_06_160415_create_model_flags_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_07_145746_create_features_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_07_145747_create_filament_feature_flags_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_042602_app_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_042617_auth_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_042617_seo_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_061704_create_tag_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_070156_create_contact_submissions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_073656_add_onboarding_to_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_081742_add_userstamps_to_contact_submissions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_120053_create_flags_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_120053_create_imports_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_120054_create_exports_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_120055_create_failed_import_rows_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_120419_create_categories_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_125751_create_changelog_entries_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_125751_create_posts_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_08_125752_create_help_articles_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154244_create_levels_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154245_create_experiences_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154246_add_level_relationship_to_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154247_create_experience_audits_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154248_create_achievements_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154249_create_achievement_user_pivot_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154250_create_streak_activities_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154251_create_streaks_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154252_create_streak_histories_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154253_add_streak_freeze_feature_columns_to_streaks_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_10_154254_remove_level_id_column_from_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151120_create_organizations_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151126_add_organization_id_to_permission_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151126_create_organization_invitations_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151126_create_organization_user_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151127_add_organization_id_to_content_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151127_backfill_organization_data', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151811_create_organization_roles_and_assign_members', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_151944_set_global_roles_organization_id_to_zero', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154344_create_plans_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154345_create_plan_features_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154346_create_plan_subscriptions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154347_create_plan_subscription_usage_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154348_remove_unique_slug_on_subscriptions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154349_update_unique_keys_on_features_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154350_remove_cancels_at_from_subscriptions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154433_create_credits_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154434_create_credit_packs_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154434_create_invoices_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154435_create_payment_gateways_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154439_create_gateway_products_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154439_create_refund_requests_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154440_add_billing_data_to_organizations_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154440_create_billing_metrics_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154440_create_webhook_logs_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_154554_add_invoice_payment_gateway_foreign_key', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_165459_create_organization_domains_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_165832_add_seat_billing_and_gateway_fields', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_13_165933_create_billing_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_023808_add_organization_id_to_webhook_logs_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_042118_create_terms_versions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_042119_create_user_terms_acceptances_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_050359_create_enterprise_inquiries_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_053530_create_voucher_scopes_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_053532_create_vouchers_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_074651_add_timezone_column_to_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_074841_create_failed_payment_attempts_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_074842_create_affiliates_and_related_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_114714_create_pan_analytics_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_115657_create_mail_templates_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_115658_create_mail_exceptions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_125120_create_shareables_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_125501_create_visibility_demos_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_14_130001_add_visibility_columns_to_visibility_demos_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_22_074937_create_telescope_entries_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_22_225924_create_organization_settings_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_000001_extend_app_and_billing_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_000002_create_mail_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_000003_create_tenancy_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_000004_create_payment_and_integration_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_000005_create_ai_and_search_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_000006_create_security_and_ux_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_000007_create_remaining_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_100000_create_setup_wizard_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_133115_create_theme_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_134258_create_pages_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_150322_add_meta_to_pages_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_150322_create_page_revisions_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_200000_extend_ai_and_tenancy_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_02_23_200001_add_url_and_broadcast_connection_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_01_111056_add_soft_deletes_to_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_000001_add_tailux_theme_fields', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_000002_add_allow_user_theme_customization', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_000003_add_allow_user_logo_upload', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_000003_add_layout_and_menu_theme_fields', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_000003_add_theme_mode_to_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_000004_add_locked_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_040756_default_allow_user_theme_customization_true', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_124707_create_audit_logs_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_07_132759_add_label_to_roles_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_08_000001_create_slug_redirects_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_08_000002_add_status_to_organization_domains_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_08_000003_create_social_accounts_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_08_000004_create_notification_preferences_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_08_000004_make_users_password_nullable', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_08_000005_add_oauth_to_auth_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_09_000001_reset_theme_to_neutral_defaults', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_10_000001_create_infrastructure_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_10_000001_create_logging_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_10_000002_extend_auth_settings_policies', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_000001_extend_tenancy_personal_org_and_share_defaults', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_062952_create_announcements_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064046_1_create_mails_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064047_2_create_mail_attachments_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064048_2_create_mail_events_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064048_add_from_to_mail_templates_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064049_2_create_mailables_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064050_3_add_unsuppressed_at_to_mail_events', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064051_4_add_tags_to_mails_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064052_4_add_transport_column_to_mails_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064053_5_change_columns_to_long_text', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_064054_5_change_link_to_long_text', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_081034_add_governor_owned_by_to_announcements_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_11_085035_add_position_to_announcements_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_12_000001_add_ai_thesys_settings', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_12_225608_add_showcase_columns_to_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_081352_create_webhook_calls_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_115015_backfill_help_article_featured_flags', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_115016_remove_is_featured_from_help_articles', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_115319_add_extra_attributes_to_credits_organizations_pages', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_131010_add_soft_deletes_to_organization_domains_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_131010_add_soft_deletes_to_organization_invitations_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_131010_add_soft_deletes_to_social_accounts_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_131011_add_soft_deletes_to_notification_preferences_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_18_131011_add_soft_deletes_to_user_terms_acceptances_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_19_150059_drop_onboarding_steps_completed_from_users_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_19_153740_drop_telescope_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_19_154211_create_health_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_19_154211_create_pulse_tables', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_19_200000_create_reports_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_19_210000_create_dashboards_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_19_210000_create_report_outputs_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_21_013513_add_embedding_to_help_articles_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_21_013514_add_embedding_to_changelog_entries_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_21_013514_add_embedding_to_posts_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_21_013515_add_embedding_to_agent_conversation_messages_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('2026_03_22_000001_update_theme_font_to_ibm_plex_sans', 1);
INSERT INTO migrations (migration, batch) VALUES ('create_data_table_audit_log_table', 1);
INSERT INTO migrations (migration, batch) VALUES ('create_data_table_saved_views_table', 1);
